---
title: "Introdução"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introducao}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Treinando o modelo - função run_train**

```{r setup , eval=F}
library(autoasn)
library(magrittr)

run_train(data_path='data',
          data_file= 'auto.xlsx',
          model_path= 'models/',
          model_name=glue::glue('auto_model_{strftime(start_time, "%Y-%m-%d--%H-%M-%S")}.rds'),
          container_url= 'https://storageaccountcsapp9d08.blob.core.windows.net/',
          key= Sys.getenv('STORAGE_ACCOUNT_KEY'),
          seed = 1992)
```


**Obtendo mpg - função get_score**

```{r , eval=F}
get_existing_model(model_path= 'models/')


input_dict = list(
  'cylinders' = 6,
  'displacement' = 320,
  'horsepower' = 150,
  'weight' = 2449,
  'acceleration' = 11.0,
  'year' = 70,
  'origin' = 1,
  'name' = 'teste01'
)

model_path = "models/"
container_url= 'https://storageaccountcsapp9d08.blob.core.windows.net/'
key=Sys.getenv('STORAGE_ACCOUNT_KEY')

model = autoasn::update_model(model_path ,container_url,key)

model = get_existing_model(model_path = "models/")

score = get_score(input_dict, model$model)
score


```


**Plotando os dados - função autoasn_plot**

```{r , eval=F}
autoasn_plot(data_path='data',
             data_file= 'auto.xlsx',
             container_url= 'https://storageaccountcsapp9d08.blob.core.windows.net/',
             key= Sys.getenv('STORAGE_ACCOUNT_KEY'))
```


